[package]
name = "ayr-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
slotmap = "1.0"
serde = { workspace = true, features = ["derive", "rc"] }
