[package]
name = "ayr-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false
proc-macro = true

[lints]
workspace = true

[dependencies]
zyn = { version = "0.5.4", features = ["ext", "derive", "pretty", "diagnostics"] }
