[package]
name = "ayr-core"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
crossbeam = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
slotmap = "1.0"

ayr-diagnostic.path = "../diagnostic"
ayr-time.path = "../time"
ayr-reflect = { path = "../reflect", features = ["serde", "macros"] }
