[package]
name = "ayr-core"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
crossbeam = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
ayr-diagnostic.path = "../diagnostic"
ayr-task.path = "../task"
ayr-time.path = "../time"
