[package]
name = "ayr-task"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
futures = "0.3"
tracing = "0.1"
crossbeam = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "time"] }
